// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai_sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAISession = `-- name: CreateAISession :one
INSERT INTO ai_sessions (user_id, command, input_summary, output_summary)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, command, input_summary, output_summary, created_at
`

type CreateAISessionParams struct {
	UserID        pgtype.UUID
	Command       string
	InputSummary  pgtype.Text
	OutputSummary pgtype.Text
}

func (q *Queries) CreateAISession(ctx context.Context, arg CreateAISessionParams) (AiSession, error) {
	row := q.db.QueryRow(ctx, createAISession,
		arg.UserID,
		arg.Command,
		arg.InputSummary,
		arg.OutputSummary,
	)
	var i AiSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Command,
		&i.InputSummary,
		&i.OutputSummary,
		&i.CreatedAt,
	)
	return i, err
}

const getAISessionsByUser = `-- name: GetAISessionsByUser :many
SELECT id, user_id, command, input_summary, output_summary, created_at FROM ai_sessions WHERE user_id = $1 ORDER BY created_at DESC
`

func (q *Queries) GetAISessionsByUser(ctx context.Context, userID pgtype.UUID) ([]AiSession, error) {
	rows, err := q.db.Query(ctx, getAISessionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AiSession
	for rows.Next() {
		var i AiSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Command,
			&i.InputSummary,
			&i.OutputSummary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
