// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNote = `-- name: CreateNote :one
INSERT INTO notes (task_id, content_json)
VALUES ($1, $2)
RETURNING id, task_id, content_json, created_at, updated_at
`

type CreateNoteParams struct {
	TaskID      pgtype.UUID
	ContentJson pgtype.Text
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, createNote, arg.TaskID, arg.ContentJson)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ContentJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNoteByTaskID = `-- name: GetNoteByTaskID :one
SELECT id, task_id, content_json, created_at, updated_at FROM notes WHERE task_id = $1
`

func (q *Queries) GetNoteByTaskID(ctx context.Context, taskID pgtype.UUID) (Note, error) {
	row := q.db.QueryRow(ctx, getNoteByTaskID, taskID)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ContentJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateNote = `-- name: UpdateNote :one
UPDATE notes SET content_json = $2, updated_at = now()
WHERE task_id = $1
RETURNING id, task_id, content_json, created_at, updated_at
`

type UpdateNoteParams struct {
	TaskID      pgtype.UUID
	ContentJson pgtype.Text
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (Note, error) {
	row := q.db.QueryRow(ctx, updateNote, arg.TaskID, arg.ContentJson)
	var i Note
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ContentJson,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
