// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (user_id, title, description, priority, column_name, position)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, title, description, status, priority, estimated_minutes, column_name, position, created_at, updated_at
`

type CreateTaskParams struct {
	UserID      pgtype.UUID
	Title       string
	Description pgtype.Text
	Priority    pgtype.Text
	ColumnName  pgtype.Text
	Position    pgtype.Int4
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.UserID,
		arg.Title,
		arg.Description,
		arg.Priority,
		arg.ColumnName,
		arg.Position,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.EstimatedMinutes,
		&i.ColumnName,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTask = `-- name: DeleteTask :exec
DELETE FROM tasks WHERE id = $1
`

func (q *Queries) DeleteTask(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTask, id)
	return err
}

const getTaskByID = `-- name: GetTaskByID :one
SELECT id, user_id, title, description, status, priority, estimated_minutes, column_name, position, created_at, updated_at FROM tasks WHERE id = $1
`

func (q *Queries) GetTaskByID(ctx context.Context, id pgtype.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTaskByID, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.EstimatedMinutes,
		&i.ColumnName,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTasksByColumn = `-- name: GetTasksByColumn :many
SELECT id, user_id, title, description, status, priority, estimated_minutes, column_name, position, created_at, updated_at FROM tasks WHERE user_id = $1 AND column_name = $2 ORDER BY position
`

type GetTasksByColumnParams struct {
	UserID     pgtype.UUID
	ColumnName pgtype.Text
}

func (q *Queries) GetTasksByColumn(ctx context.Context, arg GetTasksByColumnParams) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasksByColumn, arg.UserID, arg.ColumnName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.EstimatedMinutes,
			&i.ColumnName,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTasksByUser = `-- name: GetTasksByUser :many
SELECT id, user_id, title, description, status, priority, estimated_minutes, column_name, position, created_at, updated_at FROM tasks WHERE user_id = $1 ORDER BY column_name, position
`

func (q *Queries) GetTasksByUser(ctx context.Context, userID pgtype.UUID) ([]Task, error) {
	rows, err := q.db.Query(ctx, getTasksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.Priority,
			&i.EstimatedMinutes,
			&i.ColumnName,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks SET
    title = $2,
    description = $3,
    status = $4,
    priority = $5,
    column_name = $6,
    estimated_minutes = $7,
    position = $8,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, title, description, status, priority, estimated_minutes, column_name, position, created_at, updated_at
`

type UpdateTaskParams struct {
	ID               pgtype.UUID
	Title            string
	Description      pgtype.Text
	Status           pgtype.Text
	Priority         pgtype.Text
	ColumnName       pgtype.Text
	EstimatedMinutes pgtype.Int4
	Position         pgtype.Int4
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
		arg.ColumnName,
		arg.EstimatedMinutes,
		arg.Position,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.EstimatedMinutes,
		&i.ColumnName,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskColumn = `-- name: UpdateTaskColumn :exec
UPDATE tasks SET column_name = $2, updated_at = now()
WHERE id = $1
`

type UpdateTaskColumnParams struct {
	ID         pgtype.UUID
	ColumnName pgtype.Text
}

func (q *Queries) UpdateTaskColumn(ctx context.Context, arg UpdateTaskColumnParams) error {
	_, err := q.db.Exec(ctx, updateTaskColumn, arg.ID, arg.ColumnName)
	return err
}

const updateTaskPosition = `-- name: UpdateTaskPosition :exec
UPDATE tasks SET column_name = $2, position = $3, updated_at = now()
WHERE id = $1
`

type UpdateTaskPositionParams struct {
	ID         pgtype.UUID
	ColumnName pgtype.Text
	Position   pgtype.Int4
}

func (q *Queries) UpdateTaskPosition(ctx context.Context, arg UpdateTaskPositionParams) error {
	_, err := q.db.Exec(ctx, updateTaskPosition, arg.ID, arg.ColumnName, arg.Position)
	return err
}
