// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timeblocks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTimeBlock = `-- name: CreateTimeBlock :one
INSERT INTO time_blocks (user_id, task_id, date, start_time, end_time)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, task_id, date, start_time, end_time, completed, created_at
`

type CreateTimeBlockParams struct {
	UserID    pgtype.UUID
	TaskID    pgtype.UUID
	Date      pgtype.Date
	StartTime pgtype.Time
	EndTime   pgtype.Time
}

func (q *Queries) CreateTimeBlock(ctx context.Context, arg CreateTimeBlockParams) (TimeBlock, error) {
	row := q.db.QueryRow(ctx, createTimeBlock,
		arg.UserID,
		arg.TaskID,
		arg.Date,
		arg.StartTime,
		arg.EndTime,
	)
	var i TimeBlock
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.Date,
		&i.StartTime,
		&i.EndTime,
		&i.Completed,
		&i.CreatedAt,
	)
	return i, err
}

const deleteTimeBlock = `-- name: DeleteTimeBlock :exec
DELETE FROM time_blocks WHERE id = $1
`

func (q *Queries) DeleteTimeBlock(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTimeBlock, id)
	return err
}

const getTimeBlockByID = `-- name: GetTimeBlockByID :one
SELECT id, user_id, task_id, date, start_time, end_time, completed, created_at FROM time_blocks WHERE id = $1
`

func (q *Queries) GetTimeBlockByID(ctx context.Context, id pgtype.UUID) (TimeBlock, error) {
	row := q.db.QueryRow(ctx, getTimeBlockByID, id)
	var i TimeBlock
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.Date,
		&i.StartTime,
		&i.EndTime,
		&i.Completed,
		&i.CreatedAt,
	)
	return i, err
}

const getTimeBlocksByUser = `-- name: GetTimeBlocksByUser :many
SELECT id, user_id, task_id, date, start_time, end_time, completed, created_at FROM time_blocks WHERE user_id = $1 ORDER BY date, start_time
`

func (q *Queries) GetTimeBlocksByUser(ctx context.Context, userID pgtype.UUID) ([]TimeBlock, error) {
	rows, err := q.db.Query(ctx, getTimeBlocksByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimeBlock
	for rows.Next() {
		var i TimeBlock
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
			&i.Completed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTimeBlocksByUserDate = `-- name: GetTimeBlocksByUserDate :many
SELECT id, user_id, task_id, date, start_time, end_time, completed, created_at FROM time_blocks WHERE user_id = $1 AND date = $2 ORDER BY start_time
`

type GetTimeBlocksByUserDateParams struct {
	UserID pgtype.UUID
	Date   pgtype.Date
}

func (q *Queries) GetTimeBlocksByUserDate(ctx context.Context, arg GetTimeBlocksByUserDateParams) ([]TimeBlock, error) {
	rows, err := q.db.Query(ctx, getTimeBlocksByUserDate, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimeBlock
	for rows.Next() {
		var i TimeBlock
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TaskID,
			&i.Date,
			&i.StartTime,
			&i.EndTime,
			&i.Completed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTimeBlockCompleted = `-- name: MarkTimeBlockCompleted :exec
UPDATE time_blocks SET completed = true WHERE id = $1
`

func (q *Queries) MarkTimeBlockCompleted(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markTimeBlockCompleted, id)
	return err
}

const updateTimeBlock = `-- name: UpdateTimeBlock :one
UPDATE time_blocks SET
    task_id = $2,
    start_time = $3,
    end_time = $4,
    completed = $5
WHERE id = $1
RETURNING id, user_id, task_id, date, start_time, end_time, completed, created_at
`

type UpdateTimeBlockParams struct {
	ID        pgtype.UUID
	TaskID    pgtype.UUID
	StartTime pgtype.Time
	EndTime   pgtype.Time
	Completed pgtype.Bool
}

func (q *Queries) UpdateTimeBlock(ctx context.Context, arg UpdateTimeBlockParams) (TimeBlock, error) {
	row := q.db.QueryRow(ctx, updateTimeBlock,
		arg.ID,
		arg.TaskID,
		arg.StartTime,
		arg.EndTime,
		arg.Completed,
	)
	var i TimeBlock
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TaskID,
		&i.Date,
		&i.StartTime,
		&i.EndTime,
		&i.Completed,
		&i.CreatedAt,
	)
	return i, err
}
