// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createConfirmationToken = `-- name: CreateConfirmationToken :one
INSERT INTO confirmation_tokens (email, token, expires_at)
VALUES ($1, $2, $3)
RETURNING id, email, token, expires_at, used, created_at
`

type CreateConfirmationTokenParams struct {
	Email     string
	Token     string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateConfirmationToken(ctx context.Context, arg CreateConfirmationTokenParams) (ConfirmationToken, error) {
	row := q.db.QueryRow(ctx, createConfirmationToken, arg.Email, arg.Token, arg.ExpiresAt)
	var i ConfirmationToken
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Token,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, password_hash, supabase_id)
VALUES ($1, $2, $3, $4)
RETURNING id, email, name, supabase_id, email_confirmed, password_hash, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	Name         string
	PasswordHash string
	SupabaseID   pgtype.Text
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.PasswordHash,
		arg.SupabaseID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.SupabaseID,
		&i.EmailConfirmed,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getConfirmationToken = `-- name: GetConfirmationToken :one
SELECT id, email, token, expires_at, used, created_at FROM confirmation_tokens WHERE token = $1
`

func (q *Queries) GetConfirmationToken(ctx context.Context, token string) (ConfirmationToken, error) {
	row := q.db.QueryRow(ctx, getConfirmationToken, token)
	var i ConfirmationToken
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Token,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, supabase_id, email_confirmed, password_hash, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.SupabaseID,
		&i.EmailConfirmed,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, supabase_id, email_confirmed, password_hash, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.SupabaseID,
		&i.EmailConfirmed,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserBySupabaseID = `-- name: GetUserBySupabaseID :one
SELECT id, email, name, supabase_id, email_confirmed, password_hash, created_at, updated_at FROM users WHERE supabase_id = $1
`

func (q *Queries) GetUserBySupabaseID(ctx context.Context, supabaseID pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserBySupabaseID, supabaseID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.SupabaseID,
		&i.EmailConfirmed,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markTokenUsed = `-- name: MarkTokenUsed :exec
UPDATE confirmation_tokens SET used = true WHERE id = $1
`

func (q *Queries) MarkTokenUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markTokenUsed, id)
	return err
}

const updateEmailConfirmed = `-- name: UpdateEmailConfirmed :exec
UPDATE users SET email_confirmed = true, updated_at = now()
WHERE supabase_id = $1
`

func (q *Queries) UpdateEmailConfirmed(ctx context.Context, supabaseID pgtype.Text) error {
	_, err := q.db.Exec(ctx, updateEmailConfirmed, supabaseID)
	return err
}

const updatePasswordHash = `-- name: UpdatePasswordHash :exec
UPDATE users SET password_hash = $2, updated_at = now()
WHERE id = $1
`

type UpdatePasswordHashParams struct {
	ID           pgtype.UUID
	PasswordHash string
}

func (q *Queries) UpdatePasswordHash(ctx context.Context, arg UpdatePasswordHashParams) error {
	_, err := q.db.Exec(ctx, updatePasswordHash, arg.ID, arg.PasswordHash)
	return err
}

const updateUserSupabaseID = `-- name: UpdateUserSupabaseID :exec
UPDATE users SET supabase_id = $2, updated_at = now()
WHERE id = $1
`

type UpdateUserSupabaseIDParams struct {
	ID         pgtype.UUID
	SupabaseID pgtype.Text
}

func (q *Queries) UpdateUserSupabaseID(ctx context.Context, arg UpdateUserSupabaseIDParams) error {
	_, err := q.db.Exec(ctx, updateUserSupabaseID, arg.ID, arg.SupabaseID)
	return err
}
